### ISSUE TITLE
Contributing to ZenEx

### ISSUE THREAD

**Issue by doomspork** [otoyo/zendex#16]
Howdy @otoyo :wave: We've recently adopted Zendesk at System76 and want to leverage this library in our integration. As it stands it is missing a few endpoints we need. We'd like to contribute those changes in addition to some other minor changes, but before opening up a bunch of PRs we thought we'd talk through the changes we're making in our fork:

1. We're adding endpoints for Organizations, OrganizationMembers, and Identities. We have others on the horizon we'll be including.
1. Migrating to `Finch` in place of `HTTPoison` now that the latter is deprecated
1. Setting up GitHub Actions for `mix format`, `test`, and `credo`.
1. Expanding test coverage by using `Mox` at the HTTP layer

Are any of these changes thing you would be interested in having upstream?

**Comment by otoyo** [comment]
Thank you for using zen_ex.
Actually, I was just thinking to replace `HTTPoison` to other and use GitHub Action instead of Travis.
So I am welcome to your changes 😃

**Comment by otoyo** [comment]
Replaced httpotion with Tesla.
https://hex.pm/packages/zen_ex/0.5.0
