### ISSUE TITLE
Searching users is broken for our Zendesk instance

### ISSUE THREAD

**Issue by mathieul** [otoyo/zendex#17]
Hello,

Thank you for sharing your work, `ZenEx` is really useful and straightforward to use 👍.

I'm having an issue when searching users. For instance running:

```elixir
iex> ZenEx.Model.User.search(%{email: "test@example.com"})
%ZenEx.Collection{
  count: 1,
  decode_as: [users: [ZenEx.Entity.User]],
  entities: nil,
  next_page: nil,
  previous_page: nil
}
```

should have `:entities` set. But it doesn't because the JSON payload returned contains the list of users found in the `:users` key instead of `:results`:

```
GET https://subdomain.zendesk.com/api/v2/users/search.json?query=test

{
    "users": [
        {
            "id": 422109096513,
            "url": "https://subdomain.zendesk.com/api/v2/users/422109096513.json",
            ...
        }
    ],
    "next_page": null,
    "previous_page": null,
    "count": 1
}
```

I've temporarily fixed it for us by updating `ZenEx.Model.User.search/2` to:

```elixir
  def search(query) do
    "/api/v2/users/search.json?query=#{query}"
    |> HTTPClient.get(users: [User])
  end
```

Cheers,

Mathieu

**Comment by otoyo** [comment]
Thank you for reporting the issue.

Hmm, according to the API docs, API responds entities as `:results`.
https://developer.zendesk.com/rest_api/docs/support/search#example

I understand Zendesk API is often different from its docs.
Please wait for my fixing zen_ex.

**Comment by mathieul** [comment]
From what I understand, the doc you're mentioning above is a generic search for tickets, users, etc... And it seems to return the result in the `results` key.

But if you search for users directly, this is the relevant doc: https://developer.zendesk.com/rest_api/docs/support/users#search-users

It's a bit confusing indeed...

**Comment by otoyo** [comment]
Thank you for the additional information.
I thought User Search API responds with `results` key.
I fixed it at #18 .
Please review and try in.

**Comment by mathieul** [comment]
Hey there. Thank you so much for fixing it so quickly.

I've just tested it (commit e7ec02b8dae1e30779d60b2ba2e49c7ada9ed956) and it works great 👍

**Comment by otoyo** [comment]
Thank you for testing.
Please use [v0.4.4](https://github.com/otoyo/zen_ex/releases/tag/v0.4.4) .

**Comment by mathieul** [comment]
Hi @otoyo. When will you publish v0.4.4 to hex.pm?

**Comment by otoyo** [comment]
Sorry, I forgot publish 😅 
Now v0.4.4 is published https://hex.pm/packages/zen_ex/0.4.4
