### ISSUE TITLE
Problem during ticket creation with gzip compression

### ISSUE THREAD

**Issue by kavabata** [otoyo/zendex#21]
While ticket creation:
```ZenEx.Model.Ticket.create(%ZenEx.Entity.Ticket{subject: "TestTicket", description: "Please ignore it."})```

I'm getting error:
```
  body: %{
    "error" => "Unprocessable Entity",
    "message" => "Server could not parse JSON"
  },
```

I found that problem is related to `Tesla.Middleware.Compression` on https://github.com/otoyo/zen_ex/blob/main/lib/zen_ex/http_client.ex#L11 

Without this middleware - ticket was created successfully.
Can you remove this middleware, or make it optional?
Thanks

**Comment by otoyo** [comment]
Thank you for the bug report.
I fix it in https://github.com/otoyo/zen_ex/pull/22

Could you test this patch?
I would like to know the `get`, `create`, `update`, `delete` of Ticket does well.

**Comment by otoyo** [comment]
@kavabata could you take a look please
