### ISSUE TITLE
Ticket creation

### ISSUE THREAD

**Issue by kavabata** [otoyo/zendex#24]
Suggestion to extend TicketEntry:
* to support requestor fields
```
%TicketEntry{
...
  requester: %{
          name
          email
  }
}
```
* also good to have ability add html version of comment
```
%TicketEntry{
...
  comment: %{
        html_body: html_body
   }
}
```

**Comment by otoyo** [comment]
## requester field

Ticket entities correspond to JSON format of Ticket API. It doesn't have requester field.
You can get requesters as follows:
```elixir
{:ok, requester} = ZenEx.Model.User.show(ticket.requester_id)
```

## html version of comment

Thus ticket comment body is contained in Ticket Comment API not Ticket API, Ticket Comment entities and models need to be implemented.
If there is demand, I would consider it.
