### ISSUE TITLE
API supported params aren't being passed

### ISSUE THREAD

**Issue by poops** [otoyo/zendex#8]
I'm not able to pass params such as "role" to the User model
`users = ZenEx.Model.User.list(role: "agent").entities`
which is supported by the API
https://developer.zendesk.com/rest_api/docs/core/users#filters

It looks like `ZenEx.Query.build` only allows a few params
`@params [:ids, :per_page, :sort_order]`

Any way that limitation could be removed, so any filters passed, get passed through to the API?
I can create a PR, but wanted to check first

**Comment by otoyo** [comment]
Actually I think `@params` as whitelist is little bit strict.
Thank you for your PR.
Please check my comments and fix them. I'll cherry-pick your commits and version up.
